#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Jan 20 14:13:22 CST 2018
# SW Build 2018833 on Wed Oct  4 19:58:07 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim TB_WIFI_DECRYPT_behav -key {Behavioral:sim_1:Functional:TB_WIFI_DECRYPT} -tclbatch TB_WIFI_DECRYPT.tcl -view /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/wifi_decrypt/TB_WIFI_DECRYPT_behav.wcfg -log simulate.log
