# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/wifi_decrypt/wifi_decrypt.cache/wt [current_project]
set_property parent.project_path /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/wifi_decrypt/wifi_decrypt.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/wifi_decrypt/wifi_decrypt.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/fifo_async/bin2gray.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/uart/clkdiv.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/de0_nano_const_pkg.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/count_bin.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/crc.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/debounce.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/fifo_async/fifo_async.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/fifo_sync/fifo_sync.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sha1_pkt.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/hmac_sha1_vector.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/key_schedule.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/mmcm_base_clk.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/one_shot.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/pbkdf2_sha1.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/pbkdf2_sha1_f.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/pmk_get_from_fifo.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/pmk_put_to_fifo.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/pmk_verify.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/prescaler.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/sd_const_pkg.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/sd_controller.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/sd_transceiver.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/sd_v3.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sha1_calc.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sha1_core.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sha1_ibuffer.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sha1_schedule.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/fifo_sync/simple_dual_one_clock.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/fifo_async/simple_dual_two_clocks.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/simple_sd.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/fifo_async/sync_crossclk.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sync_pulse.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/sd/tick_extend.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/uart/uart_tx.vhd
  /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/vhd/src/wifi_decrypt.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/wifi_decrypt.xdc
set_property used_in_implementation false [get_files /home/ll/workdir/fpga_test/VHDL/wifi_decrypt/wifi_decrypt.xdc]


synth_design -top WIFI_DECRYPT -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef WIFI_DECRYPT.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file WIFI_DECRYPT_utilization_synth.rpt -pb WIFI_DECRYPT_utilization_synth.pb"
